[kubernetes]
disabled = false
[kubernetes.context_aliases]
"gke_qdoo-env-svc-02-615047_europe-west1_belgium-00" = "qdoo-svc"
"gke_qdoo-env-dev-01-069666_europe-west1_belgium-00" = "qdoo-dev"
"gke_qdoo-env-stg-01-335018_europe-west1_belgium-00" = "qdoo-stg"
"gke_qdoo-env-prod-01-529951_europe-west1_belgium-00" = "qdoo-prod"
"arn:aws:eks:eu-west-1:453429343026:cluster/general-01" = "aws-qdoo-dev"

[terraform]
format = "[$symbol$version$workspace]($style) "

[custom.fishcognito]
command = """ printf ' \\xF0\\x9F\\x91\\xBB' """
when = """ test "$fishcognito_active" = "true" """

[time]
disabled = false
format = "[$time]($style)"

[character]
success_symbol = " [➜](bold green)"
error_symbol = " [✗](bold red)"
